### ISSUE TITLE
Display gets corrupted on bogus data

### ISSUE THREAD

**Issue by veox** [goerli/netstats-server#13]
Most commonly visible on bar-graphs for block time, difficulty, transaction count...

The most common cause is someone accidentally connecting a node from network X to dashboard of network Y; but this could also happen due to malice.

In general, the dashboard is overly trusting in accepting the data fed to it as correct, and does not gracefully handle conflicts.

**Comment by 5chdn** [comment]
@veox I took your advice and moved the repository to https://github.com/goerli/ethstats-server/issues
